export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const BEGIN_PRODUCTS_DOWNLOAD = "BEGIN_PRODUCTS_DOWNLOAD";
export const PRODUCTS_DOWNLOAD_SUCCESS = "PRODUCTS_DOWNLOAD_SUCCESS";
export const PRODUCTS_DOWNLOAD_ERROR = "PRODUCTS_DOWNLOAD_ERROR";

export const GET_DELETE_PRODUCT = "GET_DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

export const GET_EDIT_PRODUCT = "GET_EDIT_PRODUCT";
export const BEGIN_EDIT_PRODUCT = "BEGIN_EDIT_PRODUCT";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
